<?php

namespace Database\Seeders;

use App\Models\Setting\SystemField;
use Illuminate\Database\Seeder;

class SystemFieldsTableSeeder extends Seeder
{
    public function run()
    {
        $system_fields = [
            [
                'name' => 'first_name',
                'label' => 'First Name',
                'type' => 1,
                'values' => null,
                'is_required' => 1,
                'order'   =>1,
                'grid'   =>'col-md-3',
                'show_on_table'=>1,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'last_name',
                'label' => 'Last Name',
                'type' => 1,
                'values' => null,
                'order'   =>2,
                'grid'   =>'col-md-3',
                'show_on_table'=>1,
                'is_required' => 1,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'mobile_number',
                'label' => 'Mobile Number',
                'type' => 2,
                'order'   =>3,
                'grid'   =>'col-md-3',
                'show_on_table'=>1,
                'values' => null,
                'is_required' => 1,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'alternate_mobile_number',
                'label' => 'Alternate Mobile Number',
                'type' => 2,
                'values' => null,
                'order'   =>4,
                'grid'   =>'col-md-3',
                'show_on_table'=>1,
                'is_required' => 0,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'social_security_number',
                'label' => 'Social Security Number',
                'type' => 2,
                'values' => null,
                'order'   =>5,
                'grid'   =>'col-md-3',
                'show_on_table'=>1,
                'is_required' => 1,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'date_of_birth',
                'label' => 'Date of Birth',
                'type' => 10,
                'values' => null,
                'order'   =>6,
                'grid'   =>'col-md-3',
                'show_on_table'=>1,
                'is_required' => 1,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'prospect',
                'label' => 'Prospect',
                'type' => 1,
                'values' => null,
                'order'   =>7,
                'grid'   =>'col-md-3',
                'show_on_table'=>1,
                'is_required' => 0,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'source',
                'label' => 'Source',
                'type' => 1,
                'values' => null,
                'order'   =>8,
                'grid'   =>'col-md-3',
                'show_on_table'=>1,
                'is_required' => 0,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'email',
                'label' => 'Email Id',
                'type' => 9,
                'values' => null,
                'order'   =>9,
                'grid'   =>'col-md-3',
                'show_on_table'=>1,
                'is_required' => 1,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'order_status',
                'label' => 'Order Status',
                'type' => 6,
                'values' => json_encode(['Sale', 'Quility done', 'Processed', 'Paid', 'Greeting call done']),
                'is_required' => 1,
                'order'   =>10,
                'grid'   =>'col-md-3',
                'show_on_table'=>1,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'zip_code',
                'label' => 'Zip Code',
                'type' => 1,
                'values' => null,
                'order'   =>11,
                'grid'   =>'col-md-3',
                'show_on_table'=>12,
                'is_required' => 1,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'previous_address',
                'label' => 'Previous Address',
                'type' => 5,
                'values' => null,
                'order'   =>12,
                'grid'   =>'col-md-3',
                'show_on_table'=>1,
                'is_required' => 0,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'full_address',
                'label' => 'Full Address',
                'type' => 5,
                'values' => null,
                'order'   =>13,
                'grid'   =>'col-md-3',
                'show_on_table'=>1,
                'is_required' => 1,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'street_address',
                'label' => 'Street Address',
                'type' => 5,
                'values' => null,
                'order'   =>14,
                'grid'   =>'col-md-3',
                'show_on_table'=>1,
                'is_required' => 0,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'city',
                'label' => 'City',
                'type' => 1,
                'values' => null,
                'order'   =>15,
                'grid'   =>'col-md-3',
                'show_on_table'=>1,
                'is_required' => 1,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'screen_shot',
                'label' => 'Screenshot',
                'type' => 7,
                'values' => null,
                'order'   =>16,
                'grid'   =>'col-md-6',
                'show_on_table'=>1,
                'is_required' => 0,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'audio',
                'label' => 'Audio',
                'type' => 7,
                'values' => null,
                'order'   =>17,
                'grid'   =>'col-md-6',
                'show_on_table'=>1,
                'is_required' => 0,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
            ]

        ];
        SystemField::insert($system_fields);
    }
}